var GAME_LEVELS = [
  ["  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x @                                                                                                                                        x!!!!!!!!!!!!",
   "  x                                                                                                                                          x!!!!!!!!!!!!",
   "  x                                                                                                                                       o  x!!!!!!!!!!!!",
   "  x                                                                                                       xxxxxxx^^^^^                       x!!!!!!!!!!!!",
   "  x                                                                                                       x                             xxxxxx!!!!!!!!!!!!",
   "  x                                                                                                       x                             x!!!!!!!!!!!!!!!!!",
   "  x                                                                                                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  x                                                                                                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  x                                                                                                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  x                                                                                                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  x                                                                                                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  x                                                                          xxxxxx                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  x                                                                                                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  x                                                                                                     ^^x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxxx     xxxxxxxxxxxx     xxxxxxx           xxxxxxxxxxxxx                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "             x     x          x     x     x           x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                                           ",
   "             x     x          x!!!!!x     x!!!!!!!!!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                                           ",
   "             x     x          x!!!!!x     x!!!!!!!!!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                                           ",
   "             xxxxxxx          xxxxxxx     xxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                           ",
   "                                                                                                                                                          ",
   "                                                                                                                                                          ",
   "                                                                                                                                                          ",
   "                                                                                                                                                          "],  



  ["  x                                                  !!!!!!!!!!!!!!!!                                                                                                                                        ",
   "  x                                                  !!!!!!!!!!!!!!!!                                                                                                                                        ",
   "  x                                                  !!!!!!!!!!!!!!!!                                                                                                                                        ",
   "  x                                                  !!!!!!!!!!!!!!!!                                                                                                                                        ",
   "  x                                                  !!!!!!!!!!!!!!!!                          xxxx                                                                                                          ",
   "  x                                                  !!!!!!!!!!!!!!!!xxxxxxxxxxx               xo x                                                                                                                     ",
   "  x                                                  !!!!!!!!!!!!!!!!          x               x  x                                                                                                           ",
   "  x                                                  !!!!!!!!!!!!!!!!          x               x  x                                                                                                            ",
   "  x                                                  !!!!!!!!!!!!!!!!          x               x  x                                                                                                            ",
   "  x                                                  !!!!!!!!!!!!!!!!          x               x  x                                                                                                             ",
   "  x                                                  !!!!!!!!!!!!!!!!          x               x  x                                                                                                             ",
   "  x                                                  !!!!!!!!!!!!!!!!xx        x               x  x                                                                                                             ",
   "  x                                                  !!!!!!!!!!!!!!!!     !    x               x  x                                                                                                             ",
   "  x                                                  !!!!!!!!!!!!!!!!     !    x               x  x                                                                                                             ",
   "  x                                                  !!!!!!!!!!!!!!!!   xx!    xvxxxxvxxxxxvxxxx  x                                                                                                               ",
   "  x @                                                !!!!!!!!!!!!!!!!     !                       x                                                                                                            ",
   "  x                                  ~~              !!!!!!!!!!!!!!!!     !                       x                                                                                                            ",
   "  x                                                  !!!!!!!!!!!!!!!!xx   !=                      x                                                                                                             ",
   "  x                                         ~~~~~~   !!!!!!!!!!!!!!!!     !xx~~~~~~~~~~~~~~~~~~~^^x                                                                                                                       ",
   "  x                                                  !!!!!!!!!!!!!!!!     !                                                                                                                                  ",
   "  x                                                  !!!!!!!!!!!!!!!!     !                                                                                                                                  ",
   "  x                                             ~~   !!!!!!!!!!!!!!!!   xx!                                                                                                                                ",
   "  x       xxxxx                                      !!!!!!!!!!!!!!!!     !                                                                                                                             ",
   "  x       x   x~~~~x            x^^                x!!!!!!!!!!!!!!!!!     !                                                                                                                                            ",
   "  x       x        x!!!!!!!!!!!!x               ~~ xxxxxxvxxxvxxxvxxx     !                                                                                                                                              ",
   "  xxx~~~~~x        x!!!!!!!!!!!!x                                         !                                                                                                                                  ",
   "                   x!!!!!!!!!!!!x                                         !                                                                                                                                  ",
   "                   xxxxxxxxxxxxxx               ~~                        !                                                                                                                                 ",
   "                                x!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxx^^^^x!                                                                                                                                          ",
   "                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!                                                                                                                                   ",
   "                                                                          !                                                                                                                                   ",
   "                                                                          !                                                                                                                                   ",
   "                                                                          !                                                                                                                                   ",
   "                                                                          !                                                                                                                                   "],  



  ["                                                                                                               x",
   "                                                                                                               x",
   "                                                                                                               x",
   "                                                                                                               x",
   "                                                                                                               x",
   "                                                                                                               x",
   "         xxxxxxxxxxx  xxxxx!xxxxx  xxxxxx!xxxxx  xxxxxxxx!xxxxxxxx  xxxxxxxxx                                  x",
   "    o    xxxxxxxxxxx  xxxxx!xxxxx  xxxxxx!xxxxx  xxxxxxxx!xxxxxxxx  xxxxxxxxx                                  x",
   "         xxxxxxxxxxx  xxxxx!xxxxx  xxxxxx!xxxxx  xxxxxxxx!xxxxxxxx  xxxxxxxxx                                  x",
   "  xxxxx  xxxxxxxxxxx  xxxxx!xxxxx  xxxxxx!xxxxx  xxxxxxxx!xxxxxxxx  xxxxxxxxx                                  x",
   "  x   x  xxxxxxxxxxx  xxxxx!xxxxx  xxxxxx!xxxxx  xxxxxxxx!xxxxxxxx  xxxxxxxxx                                  x",
   "  x @ x  xxxxxxxxxxx  xxxxx!xxxxx  xxxxxx!xxxxx  xxxxxxxx!xxxxxxxx  xxxxxxxxx                                  x",
   "  x   x  xxxxxxxxxxx  xxxxx!xxxxx  xxxxxx!xxxxx  xxxxxxxx!xxxxxxxx  xxxxxxxxx                                  x",
   "  x   x  xxxxxxxxxxx  xxxxx!xxxxx  xxxxxx!xxxxx  xxxxxxxx!xxxxxxxx  xxxxxxxxx                                  x",
   "  x   x  xxxxxxxxxxx  xxxxx!xxxxx  xxxxxx!xxxxx  xxxxxxxx!xxxxxxxx  xxxxxxxxx                                  x",
   "  x   x  xxxxxxxxxxx  xxxxxvxxxxx  xxxxxxvxxxxx  xxxxxxxxvxxxxxxxx  xxxxxxxxx            xxxxxxxx              x",
   "  x   x                                                                                          xxxxxxx       x",
   "  x   x                                                                                                        x",
   "  x   x           =                                       =                  ^                                 x",
   "  x   x^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          xxxxxxxx",
   "  x                                                |       |                 |                   xxxxxxx        ",
   "  x                                                                                      xxxxxxxx               ",
   "  x                                                                                xxxxxx                       ",
   "  x                                                                                xxx                          ",
   "  x      |        |        |       |       |                        |              xxx                          ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                          ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                "],



  ["~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "                                                           ",
   "                                                           ",
   "                                                           ",
   "                                                           ",
   "              @                                            ",
   "                                                           ",
   "                                                           ",
   "            x   x xxxx x  x     x x x xxx xxxx x           ",
   "            x   x x  x x  x     x x x  x  x  x x           ",
   "            xxxxx x  x x  x     x x x  x  x  x x           ",
   "              x   x  x x  x     x x x  x  x  x x           ",
   "              x   x  x x  x     x x x  x  x  x x           ",
   "              x   x  x x  x     x x x  x  x  x             ",
   "              x   xxxx xxxx     xxxxx xxx x  x x           ",
   "                                                           ",
   "                                                           ",
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   ]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
